export const projets = [
    {
        titre: "Kusmi Tea",
        descriptif: "Kusmi Tea est une marque de thé française. La marque propose une gamme variée de thés, y compris des infusions relaxantes",
        role: "Intégratrice Web",
        technologies: "HTML, SCSS, Gulp, Git, SFCC",
        annee: "2023/2024",
        lien: "https://www.kusmitea.com/fr/home/",
        demo: "https://drive.google.com/drive/folders/1XiTm0L496j998IqEhTMkXxar5TcmUDOV?usp=drive_link",
        slug: "kusmi-tea",
        images: ["/images/projets/kusmitea1.svg", "/images/projets/kusmitea2.webp"],
        contexte: ["Dans le cadre de mon alternance chez Kusmi Tea, j’étais la seule intégratrice au sein de l’équipe Animation / E-merchandising. Je gérais l’intégration et la mise à jour de contenu sur les 7 sites de la marque. À mon arrivée, j’ai identifié plusieurs inefficacités dans les processus de production. J’ai donc pris l’initiative de mettre en place des process organisationnels afin d’améliorer ma productivité ainsi que celle des autres équipes, tout en assurant mes missions quotidiennes.", "Stack technique utilisée quotidiennement : HTML, SCSS/SASS, JavaScript natif, Gulp, GitHub, Monday et Notion", "Mes missions :", "Intégration et mise à jour de contenus web : supports onsite, pop-ins, bannières, visuels produits, landing pages, etc.", "Création et intégration de pages web responsive.", "Intégration des articles de blog et pages SEO sur l’ensemble des sites.", "Mise en place de bonnes pratiques SEO, en collaboration avec l’équipe Acquisition.", "Mise en place de bonnes pratiques UX, en collaboration avec les équipes Design et UX.", "Contribution à l’optimisation continue des sites e-commerce.", "Participation à la conception graphique et ergonomique des sites, dans le respect des standards web et des contraintes d’intégration.", "Réalisation de benchmarks UX dans le cadre d’une veille concurrentielle.", "Force de proposition pour la création de nouvelles maquettes de landing pages ou visuels onsite."],
        cta: "Voir les projets",
    },
    {
        titre: "Etam",
        descriptif: "Etam est une marque de prêt-à-porter française. Elle propose une gamme diversifiée de lingerie, pyjamas et d'un vaste choix de vêtements.",
        role: "Intégratrice Web",
        technologies: "HTML, SCSS, Gulp, Bitbucket, SFCC",
        annee: "2021/2023",
        lien: "https://etam.com",
        demo: "https://drive.google.com/drive/folders/1npWSimaG0PFbAf6rJdrPmsGZQN04bhRb?usp=sharing",
        slug: "etam",
        images: ["/images/projets/etam1.webp", "/images/projets/etam2.webp"],
        contexte: [
            "Lors de mon alternance chez Etam, ma première expérience professionnelle, j’étais intégratrice au sein d’une équipe de deux personnes, encadrée par le responsable de l’équipe. J’assurais l’intégration et la mise à jour de contenu sur une dizaine de sites. Cette expérience m’a permis de renforcer mes compétences techniques, de développer ma capacité à travailler en équipe et de dépasser le cadre de mes missions.",
            "Stack technique utilisée quotidiennement : HTML, SCSS/SASS, JavaScript natif, Gulp, Bitbucket, Trello, Notion.",
            "Mes missions :",
            "Intégration et mise à jour de contenus web (pop-ins, bannières, landing pages…).",
            "Création et intégration de pages web responsive.",
            "Mise en place de bonnes pratiques UX, en collaboration avec l’équipe Webdesign.",
            "Participation à l’optimisation continue des sites e-commerce.",
            "Réalisation de veille concurrentielle.",
            "Amélioration des performances des sites."
        ],
        cta: "Voir les projets",
    },
    {
        titre: "Manges tes carottes",
        descriptif: "Une application mobile permettant aux utilisateurs de suivre leur consommation de viande et de trouver des recettes meat free",
        role: "Full-stack",
        technologies: "React Native, MangoDB, Express, Vercel, Node.js",
        annee: "2024",
        slug: "mange-tes-carottes",
        lien: "https://drive.google.com/drive/folders/1-DjOfFaT2kqABSdBP_b6eynrRUUMovQI?usp=drive_link",
        demo: "https://drive.google.com/drive/folders/1-DjOfFaT2kqABSdBP_b6eynrRUUMovQI?usp=drive_link",
        images: ["/images/projets/mtc_projet.webp", "/images/projets/mtc_projet2.webp"],
        contexte: 
        [
            "Mange Tes Carottes est une application destinée aux personnes souhaitant réduire leur consommation de viande, en leur permettant de suivre leurs repas. L’idée m’est venue car j’avais moi-même ce besoin : savoir combien de fois je n’avais pas mangé de viande dans la semaine, évaluer mon impact environnemental, et rester motivée à poursuivre mes efforts grâce à un suivi concret.",
            "J’ai développé cette application avec React Native. Le backend repose sur une API REST que j’ai créée avec Express et Node.js, connectée à une base de données MongoDB. L’API est déployée sur Vercel.",
            "Fonctionnalités développées :",
            "Authentification : inscription, connexion, déconnexion, vérification de compte par e-mail, modification du profil, suppression du compte.",
            "Suivi des objectifs : choix des viandes à éviter pendant l’onboarding, possibilité de modifier son objectif depuis le profil.",
            "Notifications : l’utilisateur peut activer une notification quotidienne à une heure définie, modifiable depuis son profil.",
            "Ajout des repas sans viande : l’utilisateur peut enregistrer le nombre de repas sans viande consommés, puis ajouter les détails de chaque repas.",
            "Statistiques : affichage de l’impact environnemental basé sur les repas sans viande enregistrés : litres d’eau économisés, CO₂ non émis, argent économisé et nombre total de repas végétariens. Les données sont estimées sur une base de 150g de viande par repas (3,81g CO₂ / 150g, 82,5L d’eau / 150g, 2,57€ / 150g), selon des sources fiables.",
            "Sécurité : les endpoints de l’API sont protégés par un système de token JWT intégré dans l’application, assurant que seules les personnes authentifiées puissent accéder aux fonctionnalités."
        ],
        cta: "Voir plus",
    },
    {
        titre: "Les minis déboggueurs",
        descriptif: "Une webapp créée lors d'un hackaton, projet gagnant ! Pour soutenir un jeu de société informatif sur les dangers du numérique par la ville de Rouen",
        role: "Front-end",
        technologies: "React JS, Netlify, Parcel, Github",
        annee: "2024",
        github: "https://github.com/mokonaa/les-minis-deboggueurs/tree/main",
        slug: "les-minis-deboggueurs",
        lien: "https://drive.google.com/drive/folders/1mcgPE2Ua3_Ah7iOUcyjN9qn6NfxXa-F3?usp=drive_link",
        demo: "https://les-minis-deboggueurs-game.netlify.app/",
        images: ["/images/projets/debog1.webp", "/images/projets/debog2.webp"],
        contexte: [
            "Ce projet a été réalisé dans le cadre d’un hackathon de deux semaines organisé pour la Métropole de Rouen, en collaboration avec Doralie Besnard-Guiol. Il s’agit du projet gagnant du hackaton ! Nous étions une équipe de cinq personnes : deux développeuses, deux directrices artistiques et une UI/UX designer. L’objectif était d’améliorer un prototype de jeu de société éducatif sur le numérique responsable, destiné aux enfants, en travaillant sur plusieurs axes :",
            "la direction artistique du jeu, l’expérience utilisateur et le storytelling. Nous devions également réfléchir à une intégration numérique non obligatoire, afin de proposer un support digital optionnel. Nous avons donc imaginé une webapp permettant aux enfants de suivre facilement une manche à chaque tour via un téléphone.",
            "Fonctionnalités développées :",
            "Sélection des enfants et des animateurs participant à la partie.",
            "Détermination de l’ordre de passage des joueurs (avec ou sans choix de priorité).",
            "Tri des joueurs selon leur rôle : Enfant ou Animateur.",
            "Gestion du nombre de manches dans la partie.",
            "Gestion du nombre de tours par manche.",
            "Affichage d’une fiche joueur spécifique selon le rôle (Enfant ou Animateur) au moment du tour.",
            "Attribution d’une thématique aléatoire à chaque animateur.",
            "Suivi des points de vie attribués aux enfants.",
            "Direction artistique adaptée aux différentes fonctionnalités développées."
        ]
        ,
        cta: "Démo",
    },
]
